add linking method for homebrew installed jdk

diff --git a/.github/workflows/commit.yml b/.github/workflows/commit.yml
--- a/.github/workflows/commit.yml
+++ b/.github/workflows/commit.yml
@@ -27,7 +27,7 @@ jobs:
       - name: Check libexec output
         run: |
           if ! /usr/libexec/java_home -V 2>&1 | grep -q '"Oracle Corporation" - "OpenJDK 23.0.1"'; then
-              echo "Error: asdf JDK is not detected by macOS libexec tooling."
+              echo "Error: asdf JDK is not detected by MacOS libexec tooling."
               exit 1
           fi
 
@@ -55,7 +55,7 @@ jobs:
       - name: Check libexec output
         run: |
           if ! /usr/libexec/java_home -V 2>&1 | grep -q "ASDF openjdk"; then
-              echo "Error: asdf JDK is not detected by macOS libexec tooling."
+              echo "Error: asdf JDK is not detected by MacOS libexec tooling."
               exit 1
           fi
 
@@ -78,7 +78,29 @@ jobs:
       - name: Check libexec output
         run: |
           if ! /usr/libexec/java_home -V 2>&1 | grep -q "SDKMAN Current JDK"; then
-              echo "Error: SDKMAN JDK is not detected by macOS libexec tooling."
+              echo "Error: SDKMAN JDK is not detected by MacOS libexec tooling."
+              exit 1
+          fi
+
+          echo "SDKMAN JDK detected by macOS libexec tooling."
+
+  homebrew-custom-linker:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install JDK via Homebrew
+        run: |
+          brew install openjdk
+
+      - name: Link libexec/java_home to Homebrew JDK
+        run: |
+          ./link_homebrew_jdk.sh
+
+      - name: Check libexec output
+        run: |
+          if ! /usr/libexec/java_home -V 2>&1 | grep -q "Homebrew" - "OpenJDK"; then
+              echo "Error: Homebrew JDK is not detected by MacOS libexec tooling."
               exit 1
           fi
 
